#!/usr/bin/env python
'''
Autogenerated code using arya
Original Object Document Input: 
'''

# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.fv
import cobra.model.pol
import cobra.model.vns
import cobra.model.vz
from cobra.internal.codec.xmlcodec import toXMLStr
import sys
pod_num = int(sys.argv[1])
tenant_name = sys.argv[2]
csr_ip = sys.argv[3]

lab_prefix,owner,ownersid,ownerpod = tenant_name.split("-")
tenant_login = '%s' % tenant_name

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://198.19.254.61', '%s' % tenant_login, 'p%s' % tenant_login)

md = cobra.mit.access.MoDirectory(ls)
md.login()
# the top level object on which operations will be made
polUni = cobra.model.pol.Uni('')

# build the request using cobra syntax
fvTenant = cobra.model.fv.Tenant(polUni, '%s' % tenant_name)

fvAp = cobra.model.fv.Ap(fvTenant, prio=u'unspecified', name=u'aProf')
fvAEPg = cobra.model.fv.AEPg(fvAp, matchT=u'AtleastOne', name=u'web')
fvRsCons = cobra.model.fv.RsCons(fvAEPg, tnVzBrCPName=u'web-to-app')
fvAEPg2 = cobra.model.fv.AEPg(fvAp, matchT=u'AtleastOne', name=u'app')
fvRsProv = cobra.model.fv.RsProv(fvAEPg2, tnVzBrCPName=u'web-to-app')
vzBrCP = cobra.model.vz.BrCP(fvTenant, name=u'web-to-app')
vzSubj = cobra.model.vz.Subj(vzBrCP, revFltPorts=u'yes', name=u'Subject', prio=u'unspecified', descr=u'', consMatchT=u'AtleastOne', provMatchT=u'AtleastOne')
vzRsSubjFiltAtt = cobra.model.vz.RsSubjFiltAtt(vzSubj, tnVzFilterName=u'default')
vzRsSubjGraphAtt = cobra.model.vz.RsSubjGraphAtt(vzSubj, tnVnsAbsGraphName=u'asa2-pbr-graph')
vnsLDevCtx = cobra.model.vns.LDevCtx(fvTenant, ctrctNameOrLbl=u'web-to-app', graphNameOrLbl=u'asa2-pbr-graph', nodeNameOrLbl=u'asa2-pbr')
vnsLIfCtx = cobra.model.vns.LIfCtx(vnsLDevCtx, connNameOrLbl=u'consumer')
vnsRsLIfCtxToLIf = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-consumer' % tenant_name)
vnsLIfCtx2 = cobra.model.vns.LIfCtx(vnsLDevCtx, connNameOrLbl=u'provider')
vnsRsLIfCtxToLIf2 = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx2, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-provider' % tenant_name)
vnsRsLDevCtxToLDev = cobra.model.vns.RsLDevCtxToLDev(vnsLDevCtx, tDn=u'uni/tn-%s/lDevVip-asa2-pbr'  % tenant_name)


# commit the generated code to APIC
print toXMLStr(fvTenant)
c = cobra.mit.request.ConfigRequest()
c.addMo(fvTenant)
md.commit(c)

