#!/usr/bin/env python
'''
Autogenerated code using arya
Original Object Document Input: 
'''
# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.fv
import cobra.model.pol
import cobra.model.vns
import sys
from cobra.internal.codec.xmlcodec import toXMLStr

pod_num = int(sys.argv[1])
tenant_name = sys.argv[2]
csr_ip = sys.argv[3]

lab_prefix,owner,ownersid,ownerpod = tenant_name.split("-")
tenant_login = '%s' % tenant_name

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://198.19.254.61', '%s' % tenant_login, 'p%s' % tenant_login)

md = cobra.mit.access.MoDirectory(ls)
md.login()

# the top level object on which operations will be made
polUni = cobra.model.pol.Uni('')
fvTenant = cobra.model.fv.Tenant(polUni, '%s' % tenant_name)


# build the request using cobra syntax
vnsLDevCtx = cobra.model.vns.LDevCtx(fvTenant, name=u'', descr=u'', ctrctNameOrLbl=u'web-to-app', graphNameOrLbl=u'asa2-pbr-graph', nodeNameOrLbl=u'asa2-pbr')
vnsRsLDevCtxToLDev = cobra.model.vns.RsLDevCtxToLDev(vnsLDevCtx, tDn=u'uni/tn-%s/lDevVip-asa2-pbr' % tenant_name)
vnsLIfCtx = cobra.model.vns.LIfCtx(vnsLDevCtx, permitLog=u'no', name=u'', descr=u'', connNameOrLbl=u'provider')
vnsRsLIfCtxToSvcRedirectPol = cobra.model.vns.RsLIfCtxToSvcRedirectPol(vnsLIfCtx, tDn=u'uni/tn-%s/svcCont/svcRedirectPol-pbr' % tenant_name)
vnsRsLIfCtxToBD = cobra.model.vns.RsLIfCtxToBD(vnsLIfCtx, tDn=u'uni/tn-%s/BD-pbr-bd' % tenant_name)
vnsRsLIfCtxToLIf = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-consumer' % tenant_name)
vnsLIfCtx2 = cobra.model.vns.LIfCtx(vnsLDevCtx, permitLog=u'no', name=u'', descr=u'', connNameOrLbl=u'consumer')
vnsRsLIfCtxToSvcRedirectPol2 = cobra.model.vns.RsLIfCtxToSvcRedirectPol(vnsLIfCtx2, tDn=u'uni/tn-%s/svcCont/svcRedirectPol-pbr' % tenant_name)
vnsRsLIfCtxToBD2 = cobra.model.vns.RsLIfCtxToBD(vnsLIfCtx2, tDn=u'uni/tn-%s/BD-pbr-bd' % tenant_name)
vnsRsLIfCtxToLIf2 = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx2, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-consumer' % tenant_name)

vnsRsLIfCtxToLIf = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-external' % tenant_name)

vnsRsLIfCtxToLIf2 = cobra.model.vns.RsLIfCtxToLIf(vnsLIfCtx2, tDn=u'uni/tn-%s/lDevVip-asa2-pbr/lIf-internal' % tenant_name)


# commit the generated code to APIC
print toXMLStr(fvTenant)
c = cobra.mit.request.ConfigRequest()
c.addMo(fvTenant)
md.commit(c)

